/* 상담 접수 내역 테이블 */
CREATE TABLE IF NOT EXISTS user_inquiry (
    idx int(11) NOT NULL AUTO_INCREMENT,
    c_date datetime DEFAULT NULL,
    c_name varchar(45) DEFAULT NULL,
    c_tel varchar(45) DEFAULT NULL,
    c_inflow varchar(45) DEFAULT NULL,
    c_age varchar(45) DEFAULT NULL,
    c_sex varchar(45) DEFAULT NULL,
    c_addr varchar(45) DEFAULT NULL,
    c_addr2 varchar(45) DEFAULT NULL,
    c_title1 varchar(45) DEFAULT NULL,
    c_title2 varchar(45) DEFAULT NULL,
    c_state varchar(45) DEFAULT NULL,
    c_caldate varchar(45) DEFAULT NULL,
    c_inq1 varchar(45) DEFAULT NULL,
    c_inq2 varchar(45) DEFAULT NULL,
    c_lit varchar(45) DEFAULT NULL,
    c_state2 varchar(45) DEFAULT NULL,
    c_money varchar(45) DEFAULT NULL,
    c_content text DEFAULT NULL,
    c_inflowdate datetime DEFAULT NULL,
    c_inflowurl varchar(100) DEFAULT NULL,
    c_option text DEFAULT NULL,
    c_option2 varchar(45) DEFAULT NULL,
    c_option3 varchar(45) DEFAULT NULL,
    c_option4 varchar(45) DEFAULT NULL,
    utm_source text DEFAULT NULL,
    utm_campaign text DEFAULT NULL,
    gclid varchar(255) DEFAULT NULL,
    gclid_converted_at datetime DEFAULT NULL,
    c_email varchar(100) DEFAULT NULL,
    userip varchar(45) DEFAULT NULL,
    block varchar(45) DEFAULT '0',
    PRIMARY KEY (idx)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;